# Update bundle
#   $ bundle update
# Update jekyll
#   $ bundle update jekyll
#
# To serve the content using jekyll locally
#   $ bundle exec jekyll serve
#

safe: true
lsi: false
incremental: false
highlighter: rouge

title: JOSM Scripting Plugin
email: karl.guggisberg@guggis.ch
description: >- # this means to ignore newlines until "baseurl:"
  This is the documentation for the JOSM Scripting Plugin.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Gubaer

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

aux_links:
  "GitHub":
    - "https://github.com/Gubaer/josm-scripting-plugin"
aux_links_new_tab: false

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
