name: Josm Scripting Plugin - Build

on:
  push:
    branches:
      - master
      - graalvm
  pull_request:
    branches:
      - master
  schedule:
    # build once every day
    - cron:  '0 1 * * *'

permissions:
  contents: read

jobs:
  build-01:
    name: Build plugin - JDK 11, minJosmVersion for current release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
            DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=release

  build-02:
    name: Build plugin - JDK 11, latest JOSM version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
          DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=latest

  build-03:
    name: Build plugin - JDK 11, tested JOSM version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
          DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=tested

  build-04:
    name: Build plugin - JDK 17, minJosmVersion for current release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
          DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=release -Pgraalvm.jdk=java17

  build-05:
    name: Build plugin - JDK 17, latest JOSM version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
          DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=latest -Pgraalvm.jdk=java17

  build-06:
    name: Build plugin - JDK 17, tested JOSM version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.6
        env:
          DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=tested -Pgraalvm.jdk=java17