name: Josm Scripting Plugin - Build

on:
  push:
    branches:
      - master
      - graalvm
  pull_request:
    branches:
      - master
  schedule:
    # build once every day
    - cron:  '0 1 * * *'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        josm-version:
          - latest
          - tested
          - release
        jdk:
          - 11
          - 17

    name: Build plugin - JDK ${{ matrix.jdk }}, minJosmVersion=${{ matrix.josm-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
      # headless X11 setup according to
      # https://stackoverflow.com/questions/68292797/running-java-gui-tests-on-github-using-xvfb
      - name: Set up virtual X11
        run: sudo apt-get -y install xvfb
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        env:
            DISPLAY: ":19"
        with:
          arguments: build -Pplugin.josmCompileVersion=${{ matrix.josm-version}} -Pgraalvm.jdk=java${{ matrix.jdk }}
